name: cityservices
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: 
  sdk: '>=2.17.1 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  widgetbook: 2.0.5-beta
  auto_size_text: 3.0.0
  flutter_svg: ^1.0.3
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: 
  uses-material-design: true
  assets: 
    - packages/cityservices/assets/images/burger.png
    - packages/cityservices/assets/images/ellipse3.png
    - packages/cityservices/assets/images/rectangle35.svg
    - packages/cityservices/assets/images/ellipse10.svg
    - packages/cityservices/assets/images/stars.svg
    - packages/cityservices/assets/images/maps.png
    - packages/cityservices/assets/images/oval.svg
    - packages/cityservices/assets/images/shape.svg
    - packages/cityservices/assets/images/shape.png
    - packages/cityservices/assets/images/asdasdasd.svg
    - packages/cityservices/assets/images/line.svg
    - packages/cityservices/assets/images/line2.svg
    - packages/cityservices/assets/images/iccurrent.svg
    - packages/cityservices/assets/images/icpin.svg
    - packages/cityservices/assets/images/line9.svg
    - packages/cityservices/assets/images/logo.png
    - packages/cityservices/assets/images/cap.svg
    - packages/cityservices/assets/images/wifi.png
    - packages/cityservices/assets/images/cellularconnection.png
    - packages/cityservices/assets/images/line5.svg
    - packages/cityservices/assets/images/rectangle7.png
    - packages/cityservices/assets/images/polygon1.svg
    - packages/cityservices/assets/images/rectangle9.png
    - packages/cityservices/assets/images/minivancar.svg
    - packages/cityservices/assets/images/union.png
    - packages/cityservices/assets/images/rectangle12.png
    - packages/cityservices/assets/images/rectangle13.png
    - packages/cityservices/assets/images/line1.svg
    - packages/cityservices/assets/images/line3.svg
    - packages/cityservices/assets/images/line4.svg
    - packages/cityservices/assets/images/rectangle6.png
    - packages/cityservices/assets/images/ellipse1.png
    - packages/cityservices/assets/images/ellipse2.png
    - packages/cityservices/assets/images/carblacksidesilhouette.svg
    - packages/cityservices/assets/images/vanblacktransportsideviewpointingtoleft.svg
    - packages/cityservices/assets/images/settings.png
    - packages/cityservices/assets/images/avatar.png
    - packages/cityservices/assets/images/path103.png
    - packages/cityservices/assets/images/wallet.png
    - packages/cityservices/assets/images/ellipse4.png
    - packages/cityservices/assets/images/frame1.svg
    - packages/cityservices/assets/images/polygon2.svg
    - packages/cityservices/assets/images/fill1.svg
    - packages/cityservices/assets/images/fill2.svg
    - packages/cityservices/assets/images/group245.svg
    - packages/cityservices/assets/images/fill246.svg
    - packages/cityservices/assets/images/fill248.svg
    - packages/cityservices/assets/images/fill250.svg
    - packages/cityservices/assets/images/fill251.svg
    - packages/cityservices/assets/images/fill252.svg
    - packages/cityservices/assets/images/fill253.svg
    - packages/cityservices/assets/images/fill254.svg
    - packages/cityservices/assets/images/fill255.svg
    - packages/cityservices/assets/images/fill256.svg
    - packages/cityservices/assets/images/fill257.svg
    - packages/cityservices/assets/images/fill258.svg
    - packages/cityservices/assets/images/fill259.svg
    - packages/cityservices/assets/images/fill260.svg
    - packages/cityservices/assets/images/fill261.svg
    - packages/cityservices/assets/images/fill262.svg
    - packages/cityservices/assets/images/group271.svg
    - packages/cityservices/assets/images/pointa.png
    - packages/cityservices/assets/images/sendprice.svg
    - packages/cityservices/assets/images/frame2.svg
